### ISSUE TITLE
Unexpected tag <target> in top-level of build file.

### ISSUE THREAD

**Issue by singhsurma** [lhridley/drupal7-jenkins-templates#1]
I have setup this template on new Jenkins build, however during build I am getting the following error

Unexpected tag <target> in top-level of build file.
![top-level-tag-issue](https://cloud.githubusercontent.com/assets/7009778/6824727/c1b5d03e-d31a-11e4-94fb-c5695a5fd895.png)

Let me know if I am missing something or it is an issue with XML?

**Comment by akishankar** [comment]
Hi, 
Did you figure out what was the issue. I just started working with continuous integration with jenkins and I am facing the same issue.

**Comment by singhsurma** [comment]
yes I manged to sort out and its working in good way for me. You need to check out you build.xml and set diffrent "Build project" etc according to your requirements.

**Comment by akishankar** [comment]
Can you please share demo build.properties and demo build.xml.
I am not able to find proper documentation regarding the same.

**Comment by singhsurma** [comment]
build.default.properties

=========================================================================
# The name of the project
phing.project.name = name-of-project

# Set this variable to enable the httpget proxy.
# phing.httpget.proxy = http://localhost:3128/

# The version of Drupal for the project - 6 or 7
drupal.version = 7
# The install profile to use
drupal.profile = standard
# The database url to use for site installs
drupal.db.url = sqlite:${project.drupal.dir}/database.sqlite

#The super admin account settings
drupal.admin.email = admin@example.com
drupal.admin.name = admin
drupal.admin.pass = 1admin1

#The Drupal site information
drupal.sitename = "New Jenkins Site Install"
drupal.sitemail = admin@example.com

# The drupal.uri, needed if you want to run the tests.
# Ex: drupal.uri = http://localhost/drupal7
# drupal.uri =
# Should we update the RewriteBase directive in .htaccess?
# Ex: drupal.rewritebase = /drupal7
# drupal.rewritebase =

# Options to build the project using drush_make
# The make file for the project
# drupal.make.file = name-of-project.make
# Whether to include core or not
# drupal.make.nocore = 1
# The directory to make the site in relative to the project root directory
# drupal.make.dir = site

# The directory containing the modules and themes for the project relative to the drupal root directory. If using Drush Make this is also where modules, themes, libraries etc. will be downloaded to.
project.code.dir = sites/all
# A common prefix for modules developed for the site e.g. your_prefix_your_module
project.code.prefix = your_prefix
# The names of other modules and themes developed for the site seperated by whitespace
project.code.custom = your_theme other_module

# The repository to clone for Phing PHPLoc task
phing.phploc.repository.url = https://github.com/raphaelstolt/phploc-phing.git
phing.phploc.repository.revision = 1.6.1

# The repository to clone for Phing Drush task
phing.drush.repository.url = https://github.com/kasperg/phing-drush-task.git
phing.drush.repository.revision = HEAD

# The repository to clone for PHP CodeSniffer coding standards task
# NB: This is only required if using the phpcs target / PHP_Codesniffer
phpcs.drupalcs.repository.url = https://github.com/ericduran/drupalcs.git

# The url to the jslint4java to use
jslint4java.url = http://jslint4java.googlecode.com/files/jslint4java-2.0.0-dist.zip

# The version of jslint to use
jslint.repository.url = https://github.com/mikewest/JSLint.git
# The file within the repository containing jslint
jslint.file = fulljslint.js

# The version of csslint to use
csslint.repository.url = https://github.com/stubbornella/csslint.git
csslint.repository.revision = v0.9.9

# The csslint rules to use
# The current selection is based on discussion here: http://mattwilcox.net/archive/entry/id/1054/
csslint.rules = display-property-grouping,duplicate-properties,empty-rules,known-properties,box-sizing,compatible-vendor-prefixes,gradients,vendor-prefix,import,zero-units,shorthand,important
# The csslint rules which should cause the build to break if detected
csslint.rules.break = parsing-errors


# The url from where to download rhino
rhino.url = http://ftp.mozilla.org/pub/mozilla.org/js/rhino1_7R3.zip


=========================================================================

**Comment by singhsurma** [comment]
here you can get sample how I am using:

https://gist.github.com/singhsurma/09604562cf874cda2896

**Comment by akishankar** [comment]
Thanks, I will definitely go through the solution and the link provided.

**Comment by singhsurma** [comment]
No problem!

**Comment by akishankar** [comment]
As I can see that the build.xml has been extensively modified and I assume that these modifications are solely related to project work.
I am just trying to set up a working dummy, are all these modifications need for that as well.

**Comment by ruby232** [comment]
Same error
